/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Usuario;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import serviceImpl.UsuarioServiceImpl;

/**
 *
 * @author User
 */
public class VentanaRegistroUsuario extends javax.swing.JFrame {

   // Connection con = null;
    //Statement stmt = null;
    
    public VentanaRegistroUsuario() {
        initComponents();
        
       this.setResizable(false);
       this.setLocationRelativeTo(null);
       
        txt_apellido1.setBackground(new java.awt.Color(180,180,180,180));
        txt_apellido2.setBackground(new java.awt.Color(180,180,180,180));
        txt_nombre.setBackground(new java.awt.Color(180,180,180,180));
        txt_documento.setBackground(new java.awt.Color(180,180,180,180));
        txt_correo.setBackground(new java.awt.Color(180,180,180,180));
        txt_direccion.setBackground(new java.awt.Color(180,180,180,180));
        txt_telefono.setBackground(new java.awt.Color(180,180,180,180));
        txt_idasignado.setBackground(new java.awt.Color(180,180,180,180));
        
        cmb_tipo_documento.setBackground(new java.awt.Color(80,80,80,80));
        cmb_sexo.setBackground(new java.awt.Color(80,80,80,80));
        cmb_rol.setBackground(new java.awt.Color(80,80,80,80));
        cmb_departamento.setBackground(new java.awt.Color(80,80,80,80));
        cmb_municipio.setBackground(new java.awt.Color(80,80,80,80));
        
        btn_guardar.setBackground(new java.awt.Color(80,80,80,80));
        btn_limpiar.setBackground(new java.awt.Color(80,80,80,80));
        btn_cerrar.setBackground(new java.awt.Color(80,80,80,80));
        
        jlabelidentidad.setBackground(new java.awt.Color(120,120,120,120));
        jlabelidentidad1.setBackground(new java.awt.Color(120,120,120,120));
        
        pasf_contraseña.setBackground(new java.awt.Color(180,180,180,180));
        pasf_confirmacion.setBackground(new java.awt.Color(180,180,180,180));
        
        checkbox.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_documento = new javax.swing.JTextField();
        txt_apellido1 = new javax.swing.JTextField();
        txt_apellido2 = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_idasignado = new javax.swing.JTextField();
        cmb_tipo_documento = new javax.swing.JComboBox<>();
        cmb_sexo = new javax.swing.JComboBox<>();
        cmb_rol = new javax.swing.JComboBox<>();
        cmb_departamento = new javax.swing.JComboBox<>();
        cmb_municipio = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        pasf_confirmacion = new javax.swing.JPasswordField();
        pasf_contraseña = new javax.swing.JPasswordField();
        checkbox = new java.awt.Checkbox();
        jlabelidentidad = new javax.swing.JLabel();
        jlabelidentidad1 = new javax.swing.JLabel();
        RegistroUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rol");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo documento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero Identidad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo electronico");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirmar Contraseña");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Primer apellido");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID asignado");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Municipio");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Departamento");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Segundo apellido");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        txt_correo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 390, 30));

        txt_nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 270, 30));

        txt_documento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoActionPerformed(evt);
            }
        });
        txt_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_documentoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 170, 30));

        txt_apellido1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido1ActionPerformed(evt);
            }
        });
        txt_apellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellido1KeyTyped(evt);
            }
        });
        jPanel2.add(txt_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 170, 30));

        txt_apellido2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido2ActionPerformed(evt);
            }
        });
        txt_apellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellido2KeyTyped(evt);
            }
        });
        jPanel2.add(txt_apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 170, 30));

        txt_direccion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        jPanel2.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 370, 30));

        txt_telefono.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 210, 30));

        txt_idasignado.setEditable(false);
        txt_idasignado.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txt_idasignado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idasignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idasignadoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_idasignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 170, 30));

        cmb_tipo_documento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmb_tipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de Ciudadanía", "Cédula de Extrangeria", "Permiso Especial Permanencia", "Salvoconducto", "Pasaporte" }));
        cmb_tipo_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipo_documentoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_tipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 170, 30));

        cmb_sexo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        cmb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sexoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 190, 30));

        cmb_rol.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Comprador", "Funcionario" }));
        cmb_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rolActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 170, 30));

        cmb_departamento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmb_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Norte de Santander", "Bogota" }));
        cmb_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departamentoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 210, 30));

        cmb_municipio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmb_municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bogota" }));
        cmb_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_municipioActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 190, 30));

        btn_guardar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 100, -1));

        btn_limpiar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btn_limpiar.setText("Limpiar");
        jPanel2.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 100, -1));

        btn_cerrar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 100, -1));

        pasf_confirmacion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pasf_confirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(pasf_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 190, 30));

        pasf_contraseña.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pasf_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(pasf_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 190, 30));

        checkbox.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setLabel("He leido y acepto los terminos y condiciones la politica de privacidad de CarSystem");
        jPanel2.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 450, 20));

        jlabelidentidad.setBackground(new java.awt.Color(0, 102, 102));
        jlabelidentidad.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlabelidentidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 2));
        jlabelidentidad.setOpaque(true);
        jPanel2.add(jlabelidentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 880, 330));

        jlabelidentidad1.setBackground(new java.awt.Color(0, 102, 102));
        jlabelidentidad1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlabelidentidad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 2));
        jlabelidentidad1.setOpaque(true);
        jPanel2.add(jlabelidentidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 880, 130));

        RegistroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo CarSystem.png"))); // NOI18N
        jPanel2.add(RegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido1ActionPerformed

    private void txt_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido2ActionPerformed

    private void cmb_tipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipo_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipo_documentoActionPerformed

    private void cmb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sexoActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void cmb_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rolActionPerformed

    private void cmb_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departamentoActionPerformed

    private void txt_idasignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idasignadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idasignadoActionPerformed

    private void txt_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_documentoKeyTyped
        
        char a = evt.getKeyChar();
        if((a<'0' || a>'9'))evt.consume();
        
         if(txt_documento.getText().length() >=15){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }       
        
    }//GEN-LAST:event_txt_documentoKeyTyped

    private void txt_apellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellido1KeyTyped

        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' '))evt.consume();

        if(txt_apellido1.getText().length() >=15){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_apellido1KeyTyped

    private void txt_apellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellido2KeyTyped
  
        char b = evt.getKeyChar();
        if((b<'a' || b>'z') && (b<'A' || b>'Z') && (b<' ' || b>' '))evt.consume();
        
        if(txt_apellido2.getText().length() >=15){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_apellido2KeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
       
        char d = evt.getKeyChar();
        if((d<'a' || d>'z') && (d<'A' || d>'Z') && (d<' ' || d>' '))evt.consume();
 
        if(txt_nombre.getText().length() >=25){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        
        char a = evt.getKeyChar();
        if((a<'0' || a>'9'))evt.consume();
        
        if(txt_telefono.getText().length() >=10){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        String cadena1,cadena2,cadena3,cadena4,cadena5,cadena6,cadena7,cadena8,cadena9,cadena10,cadena11,cadena12,cadena13,cadena14,cadena15;
        
        cadena1 = txt_documento.getText();
        cadena2 = cmb_tipo_documento.getSelectedItem().toString();       
        cadena3 = txt_apellido1.getText();
        cadena4 = txt_apellido2.getText();
        cadena5 = txt_nombre.getText();
        cadena7 = cmb_sexo.getSelectedItem().toString();        
        cadena8 = txt_correo.getText();
        cadena9 = txt_direccion.getText();
        cadena10 = cmb_departamento.getSelectedItem().toString();
        cadena11 = cmb_municipio.getSelectedItem().toString();      
        cadena12 = txt_telefono.getText();
        cadena13 = cmb_rol.getSelectedItem().toString();
        cadena14= pasf_contraseña.getText().toString();
        cadena15= pasf_confirmacion.getText().toString();
        
        if (txt_documento.getText().equals("")
           || (cmb_tipo_documento.getSelectedItem().equals(null))       
           || (txt_apellido1.getText().equals("")) 
           || (txt_apellido2.getText().equals(""))
           || (txt_nombre.getText().equals(""))
           || (cmb_sexo.getSelectedItem().equals(null))     
           || (txt_correo.getText().equals(""))
           || (txt_direccion.getText().equals(""))
           || (cmb_departamento.getSelectedItem().equals(null))
           || (cmb_municipio.getSelectedItem().equals(null))  
           || (txt_telefono.getText().equals("")) 
           || (cmb_rol.getSelectedItem().equals(null))    
           || (pasf_contraseña.getText().equals("")) 
           || (pasf_confirmacion.getText().equals(""))) 

            {
            
        javax.swing.JOptionPane.showMessageDialog(this,"Debe diligenciar todos los campos \n","Error!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        txt_nombre.requestFocus();
        } else {
        UsuarioServiceImpl usuarioServicio = new UsuarioServiceImpl();
        
        Usuario usuario = new Usuario("CE", Integer.parseInt(txt_documento.getText()), txt_nombre.getText(), txt_apellido1.getText(), txt_direccion.getText(), txt_telefono.getText(), txt_correo.getText(), pasf_contraseña.getText(), 2);
        
        usuarioServicio.guardar(usuario);
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cmb_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_municipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegistroUsuario;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private java.awt.Checkbox checkbox;
    private javax.swing.JComboBox<String> cmb_departamento;
    private javax.swing.JComboBox<String> cmb_municipio;
    private javax.swing.JComboBox<String> cmb_rol;
    private javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JComboBox<String> cmb_tipo_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabelidentidad;
    private javax.swing.JLabel jlabelidentidad1;
    private javax.swing.JPasswordField pasf_confirmacion;
    private javax.swing.JPasswordField pasf_contraseña;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_apellido2;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JTextField txt_idasignado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
